version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - api:/usr/app/src
    depends_on:
      - dbpostgres
    networks:
      - sanedge


  dbpostgres:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    networks:
      - sanedge
    restart: unless-stopped

volumes:
  api:
  database:

networks:
  sanedge:
    driver: bridge